FROM ruby:2.2

COPY acceptance_tests /code
WORKDIR /code
RUN bundle install --deployment
RUN mkdir /tmp/phantomjs_install
WORKDIR /tmp/phantomjs_install
RUN curl -L --retry 5 -O https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 && \
    bunzip2 phantomjs-2.1.1-linux-x86_64.tar.bz2 && \
    tar xf phantomjs-2.1.1-linux-x86_64.tar && \
    mkdir -p $HOME/.phantomjs/2.1.1/platform && \
    mv /tmp/phantomjs_install/phantomjs-2.1.1-linux-x86_64 $HOME/.phantomjs/2.1.1/x86_64-linux && \
    rm -rf /code/features && \
    rm -rf /tmp/phantomjs_install

